version: 1.1.{build}

configuration: Release

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  project_feed: true

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build NOpenPage --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack NOpenPage --configuration %CONFIGURATION% --include-symbols --no-build --output ..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: dotnet test NOpenPage.Specs\NOpenPage.Specs.csproj --configuration %CONFIGURATION%
  - cmd: dotnet test NOpenPage.Examples.SpecFlow\NOpenPage.Examples.SpecFlow.csproj --configuration %CONFIGURATION%

artifacts:
  - path: nupkgs\*.nupkg

cache:
  - '%USERPROFILE%\.nuget\packages'
