version: 1.1.{build}
before_build:
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build -c=Release /p:Version %APPVEYOR_BUILD_VERSION%
after_build:
  - cmd: dotnet pack .\NOpenPage\NOpenPage.csproj --no-build -c Release --include-symbols /p:Version=%APPVEYOR_BUILD_VERSION% -o artifacts
test_script:
  - cmd: dotnet test --no-build -c=Release .\NOpenPage.Specs\NOpenPage.Specs.csproj
  - cmd: dotnet test --no-build -c=Release .\NOpenPage.Examples.SpecFlow\NOpenPage.Examples.SpecFlow.csproj
artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
cache:
  - '%USERPROFILE%\.nuget\packages'
