version: 1.1.{build}
configuration: Release
image: Visual Studio 2017
before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal
build_script:
  - cmd: dotnet build NOpenPage\NOpenPage.csproj --configuration %CONFIGURATION% /p:Version %APPVEYOR_BUILD_VERSION%
after_build:
  - cmd: dotnet pack NOpenPage\NOpenPage.csproj --configuration %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION% --no-build --include-symbols
test_script:
  - cmd: dotnet test NOpenPage.Specs\NOpenPage.Specs.csproj --configuration %CONFIGURATION%
  - cmd: dotnet test NOpenPage.Examples.SpecFlow\NOpenPage.Examples.SpecFlow.csproj --configuration %CONFIGURATION%
artifacts:
  - path: '**\*.nupkg'
cache:
  - '%USERPROFILE%\.nuget\packages'
